# Generated by Django 5.0.7 on 2024-07-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consoleitem",
            name="company",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="consoleitem",
            name="description",
            field=models.CharField(default=None, max_length=1200),
        ),
        migrations.AddField(
            model_name="consoleitem",
            name="image",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="consoleitem",
            name="original_price",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="consoleitem",
            name="obtained",
            field=models.BooleanField(default=False),
        ),
    ]
