# Generated by Django 5.0.7 on 2024-08-17 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_list', '0002_consoleitem_company_consoleitem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoleitem',
            name='obtained',
        ),
        migrations.CreateModel(
            name='UserConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtained', models.DateTimeField(auto_now_add=True)),
                ('console_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_list.consoleitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'console_item')},
            },
        ),
    ]
