# Generated by Django 5.0.7 on 2024-08-20 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_list', '0003_remove_consoleitem_obtained_userconsole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
